### ISSUE TITLE
can't add new faculty as second drop down list says..No Record found.

### ISSUE THREAD

**Issue by Vineet279** [D-storm/GTU-Student-Attendance-System#10]

**Comment by D-storm** [comment]
To add a faculty, you need to have following:
1. Check if you have added Institutes, Programme and Department.
2. Check if you have added IPD mapping i.e. Institute, Programme and Department using "IPD Mapping" option from "Masters" menu item. This is necessary because it tells that Institute X offers Programme Y in Department Z.
